// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPI_PROGRAMACION;

#nullable disable

namespace WEBAPI_PROGRAMACION.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LenguajeSistema", b =>
                {
                    b.Property<int>("LenguajesLenguajeId")
                        .HasColumnType("int");

                    b.Property<int>("SistemasSistemaId")
                        .HasColumnType("int");

                    b.HasKey("LenguajesLenguajeId", "SistemasSistemaId");

                    b.HasIndex("SistemasSistemaId");

                    b.ToTable("LenguajeSistema", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Lenguaje", b =>
                {
                    b.Property<int>("LenguajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LenguajeId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("LenguajeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LenguajeId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Lenguajes", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("ImgProduct")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Programador", b =>
                {
                    b.Property<int>("ProgramadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramadorId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramadorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProgramadorId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Programadores", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Sistema", b =>
                {
                    b.Property<int>("SistemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SistemaId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("SistemaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SistemaId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Sistemas", (string)null);
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.SistemaProgramador", b =>
                {
                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramadorId")
                        .HasColumnType("int");

                    b.Property<string>("Desarrollador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SistemaId", "ProgramadorId");

                    b.HasIndex("ProgramadorId");

                    b.ToTable("SP", (string)null);
                });

            modelBuilder.Entity("LenguajeSistema", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Lenguaje", null)
                        .WithMany()
                        .HasForeignKey("LenguajesLenguajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBAPI_PROGRAMACION.Models.Sistema", null)
                        .WithMany()
                        .HasForeignKey("SistemasSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Category", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Lenguaje", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Estado", "Estado")
                        .WithMany("Lenguaje")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Product", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBAPI_PROGRAMACION.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Programador", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Sistema", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Estado", "Estado")
                        .WithMany("Sistema")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.SistemaProgramador", b =>
                {
                    b.HasOne("WEBAPI_PROGRAMACION.Models.Programador", "Programador")
                        .WithMany("SP")
                        .HasForeignKey("ProgramadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBAPI_PROGRAMACION.Models.Sistema", "Sistema")
                        .WithMany("SP")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programador");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Estado", b =>
                {
                    b.Navigation("Lenguaje");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Programador", b =>
                {
                    b.Navigation("SP");
                });

            modelBuilder.Entity("WEBAPI_PROGRAMACION.Models.Sistema", b =>
                {
                    b.Navigation("SP");
                });
#pragma warning restore 612, 618
        }
    }
}
